name: Release docker images

on:
  workflow_dispatch:
    branches: [master]

jobs:
  app-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: npm run build:core


      - name: Prepare .npmrc
        run:
          - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=$NPM_PUBLISH_TOKEN">.npmrc

      - name: Build
        run:
          - npm run build:core

      - name: NPM
        run:
          - npm publish -w packages/core


