version: "3.5"

services:
  dev:
    container_name: wsb-harpoon-dev
    build: ./docker
    volumes:
      - ./:/app
      - ./docker/volumes/ws-harpoon:/root/wsb-harpoon
      - /root/.npm
  dev-docs:
    container_name: wsb-harpoon-docs
    build: ./docker
    command:
      - npm run docs:dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app

