
name: QA
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci -w qa/eslint
      - run: npm run lint
